---
- hosts: all

  vars:
    use_become: "{{ ansible_os_family != 'Darwin' }}"

  tasks:
    - name: Install common
      ansible.builtin.package:
        become: "{{ use_become }}"
        name:
          - git
          - vim
          - htop
          - xz-utils
          - golang
          - fail2ban
        state: present
