name: Matrix build on multiple operating systems

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, fedora-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install ansible

      - name: Run playbook
        run: |
          source env/bin/activate
          ansible-playbook playbook.yml -vvv
