name: Matrix build on multiple operating systems

on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "bugfix/*"
  pull_request:
    branches:
      - "main"
      - "feature/*"
      - "bugfix/*"
  schedule:
    - cron: '0 0 * * 0' # Scheduled to run every Sunday at 12:00 AM
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Show available MariaDB versions from apt cache
        run: sudo apt-cache search mariadb-server

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install ansible

      - name: Run playbook
        run: |
          source env/bin/activate
          ansible-galaxy install -r requirements.yml
          ansible-playbook playbook.yml --tags=server,workstation,friend,debug -vvv
